name: CI-CD pipeline
on:
  push:
    branches: [ "main" ]

jobs:
    CI-JOBS:
        runs-on: ubuntu-latest
        steps:
            - name: Checkouts code on github hosted runner
              uses: actions/checkout@v4
            - name: vertify files
              run: |
                echo " Files in the repository: "
                ls
                
            - name: validate index file presence
              run: |
                if [ -f index.html ]; then
                echo "index.html file is present."
                else
                echo "index. html file is missing!"
                exit 1
                fi

            - name: artifact upload
              uses: actions/upload-artifact@v3
              with:
                name: index-file
                path: index.html




            
